#!/bin/bash
# run_gvsoc_figure5.sh
#
# Reproduce Figure 5: compare GVSoC real computation delays vs no-delay (onestep) baseline.
#
# Each experiment runs the acc_example MPC with 40 time steps in serial mode:
#   1. "GVSoC - Real Delays"          (in-the-loop_delay_provider: gvsoc)
#   2. "Baseline - No Delay (Onestep)" (in-the-loop_delay_provider: onestep)
#
# The GVSoC experiment uses gvsoc_flask_server.py (HTTP transport) because the
# Docker container's SHARC calls the wrapper via pipes, and the wrapper talks to
# the host-side Flask server to run the actual GVSoC binary.
#
# The onestep experiment skips the wrapper entirely — SHARC computes a
# one-step delay natively without calling GVSoC.
#
# Usage:
#   cd ~/Repositorios/SHARC_RISCV
#   source venv/bin/activate
#   bash SHARCBRIDGE/scripts/run_gvsoc_figure5.sh
#
# Results:
#   /tmp/sharc_figure5/<timestamp>/
#     gvsoc-real-delays/simulation_data_incremental.json
#     onestep-baseline/simulation_data_incremental.json
#     plots.png  (generated by SHARC)

set -euo pipefail

# ── Paths ─────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SHARCBRIDGE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_DIR="$(cd "$SHARCBRIDGE_DIR/.." && pwd)"

WRAPPER_HOST="$SHARCBRIDGE_DIR/sharc_patches/acc_example/gvsoc_controller_wrapper_v2.py"
FLASK_SERVER="$SCRIPT_DIR/gvsoc_flask_server.py"
VENV_ACTIVATE="$REPO_DIR/venv/bin/activate"
CONFIG_DOCKER="/home/dcuser/examples/acc_example/simulation_configs/gvsoc_figure5.json"
CONFIG_HOST="$REPO_DIR/sharc_original/examples/acc_example/simulation_configs/gvsoc_figure5.json"

FLASK_PORT="${FLASK_PORT:-5000}"
GVSOC_HOST="${GVSOC_HOST:-127.0.0.1}"
TIMESTAMP=$(date +%Y-%m-%d--%H-%M-%S)
EXP_DIR="/tmp/sharc_figure5/$TIMESTAMP"
DOCKER_ENV_ARGS=()
if [ -n "${GVSOC_CHIP_CYCLE_NS:-}" ]; then
    DOCKER_ENV_ARGS+=(-e "GVSOC_CHIP_CYCLE_NS=${GVSOC_CHIP_CYCLE_NS}")
fi

# ── Colors ───────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

FLASK_PID=""
SHARC_CONTAINER="sharc_figure5_main"

# ── Cleanup ───────────────────────────────────────────────────────────────────
cleanup() {
    local exit_code=$?
    echo -e "\n${YELLOW}[Cleanup] Stopping containers and server...${NC}"
    docker stop "$SHARC_CONTAINER" 2>/dev/null || true
    docker stop sharc_figure5_wrapper 2>/dev/null || true
    if [ -n "$FLASK_PID" ] && kill -0 "$FLASK_PID" 2>/dev/null; then
        curl -sf -X POST "http://localhost:${FLASK_PORT}/shutdown" -o /dev/null 2>/dev/null || true
        sleep 0.5
        kill "$FLASK_PID" 2>/dev/null || true
    fi
    if [ $exit_code -eq 0 ]; then
        echo -e "${GREEN}[Cleanup] Done${NC}"
    else
        echo -e "${RED}[Cleanup] Exited with code $exit_code${NC}"
    fi
    exit $exit_code
}
trap cleanup EXIT INT TERM

echo -e "${CYAN}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║   SHARC + GVSoC: Figure 5 — Real Delays vs Onestep          ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════════════════════╝${NC}"
echo -e "   Output dir: $EXP_DIR"
echo -e "   Config: $CONFIG_HOST"
if [ -n "${GVSOC_CHIP_CYCLE_NS:-}" ]; then
    echo -e "   Cycle ns: ${GVSOC_CHIP_CYCLE_NS} (from env)"
fi

# ── Step 1: Activate venv + install deps ─────────────────────────────────────
echo -e "\n${YELLOW}[1/7] Activating venv and checking dependencies...${NC}"
# shellcheck source=/dev/null
source "$VENV_ACTIVATE"
pip install flask requests -q
echo -e "${GREEN}✓ Dependencies ready${NC}"

# ── Step 2: Check config and wrapper ─────────────────────────────────────────
echo -e "\n${YELLOW}[2/7] Checking config and wrapper...${NC}"

if [ ! -f "$CONFIG_HOST" ]; then
    echo -e "${RED}ERROR: Config not found: $CONFIG_HOST${NC}"
    exit 1
fi

EXPERIMENT_COUNT=$(python3 -c "
import json
with open('$CONFIG_HOST') as f:
    d = json.load(f)
print(len(d))
")
echo "   Config has $EXPERIMENT_COUNT experiments"
if [ "$EXPERIMENT_COUNT" -ne 2 ]; then
    echo -e "${RED}ERROR: Expected 2 experiments in $CONFIG_HOST, got $EXPERIMENT_COUNT${NC}"
    exit 1
fi

if ! grep -q "GVSoCHTTPClient" "$WRAPPER_HOST"; then
    echo -e "${RED}ERROR: Wrapper does not have GVSoCHTTPClient: $WRAPPER_HOST${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Config OK (2 experiments), wrapper OK${NC}"

# ── Step 3: Start Flask server ────────────────────────────────────────────────
echo -e "\n${YELLOW}[3/7] Starting Flask server on port ${FLASK_PORT}...${NC}"
if curl -sf "http://localhost:${FLASK_PORT}/health" -o /dev/null 2>/dev/null; then
    echo -e "${GREEN}✓ Flask already running — reusing it${NC}"
    FLASK_PID=""
else
    python3 "$FLASK_SERVER" \
        --host 0.0.0.0 \
        --port "$FLASK_PORT" \
        --skip-validation \
        > /tmp/flask_figure5.log 2>&1 &
    FLASK_PID=$!
    echo "   Flask PID: $FLASK_PID (logs: /tmp/flask_figure5.log)"

    WAITED=0
    until curl -sf "http://localhost:${FLASK_PORT}/health" -o /dev/null 2>/dev/null; do
        sleep 1; WAITED=$((WAITED + 1)); echo -n "."
        if [ $WAITED -ge 15 ]; then
            echo -e "\n${RED}ERROR: Flask did not start within 15s${NC}"
            cat /tmp/flask_figure5.log
            exit 1
        fi
    done
    echo -e "\n${GREEN}✓ Flask ready at http://localhost:${FLASK_PORT}${NC}"
fi

# ── Step 4: Clean workspace ───────────────────────────────────────────────────
echo -e "\n${YELLOW}[4/7] Preparing experiment workspace...${NC}"
rm -rf "$EXP_DIR"
mkdir -p "$EXP_DIR"
echo -e "${GREEN}✓ Clean workspace: $EXP_DIR${NC}"

# ── Step 5: Start SHARC with gvsoc_figure5.json ───────────────────────────────
echo -e "\n${YELLOW}[5/7] Starting SHARC (gvsoc_figure5.json, 2 experiments)...${NC}"
echo "   Note: SHARC runs both experiments sequentially inside the container."
echo "         The GVSoC wrapper runs natively inside the SHARC container."

docker run \
    --name "$SHARC_CONTAINER" \
    --network=host \
    "${DOCKER_ENV_ARGS[@]}" \
    -v "$EXP_DIR:/home/dcuser/examples/acc_example/experiments" \
    -v "$WRAPPER_HOST:/home/dcuser/examples/acc_example/gvsoc_controller_wrapper_v2.py" \
    -v "$CONFIG_HOST:$CONFIG_DOCKER:ro" \
    -w /home/dcuser/examples/acc_example \
    sharc-gvsoc:latest \
    sharc --config_filename gvsoc_figure5.json

SHARC_EXIT=$?
if [ $SHARC_EXIT -ne 0 ]; then
    echo -e "${RED}ERROR: SHARC execution failed with code $SHARC_EXIT${NC}"
    exit 1
fi
echo -e "${GREEN}✓ SHARC container finished (name: $SHARC_CONTAINER)${NC}"

# ── Step 7: Verify results ────────────────────────────────────────────────────
echo -e "\n${YELLOW}[7/7] Verifying results...${NC}"

DATA_FILES=$(find "$EXP_DIR" -name "simulation_data_incremental.json" 2>/dev/null | sort)
DATA_COUNT=$(echo "$DATA_FILES" | grep -c "simulation_data_incremental" || true)

echo "   Found $DATA_COUNT simulation_data_incremental.json files"
echo "$DATA_FILES"

python3 - "$EXP_DIR" <<'PYEOF'
import sys, json, os

exp_dir = sys.argv[1]
data_files = []
for root, dirs, files in os.walk(exp_dir):
    for f in files:
        if f == 'simulation_data_incremental.json':
            data_files.append(os.path.join(root, f))

data_files.sort()

if len(data_files) < 1:
    print(f"ERROR: No simulation_data_incremental.json found in {exp_dir}")
    sys.exit(1)

print(f"\n  Found {len(data_files)} experiment output(s):")
for path in data_files:
    with open(path) as f:
        d = json.load(f)
    x = d.get('x', [])
    u = d.get('u', [])
    t = d.get('t', [])
    n = len(t)
    relpath = os.path.relpath(path, exp_dir)
    print(f"\n  [{relpath}]")
    print(f"    n_samples: {n}")
    print(f"    x[0]:  {x[0] if x else 'N/A'}")
    print(f"    x[-1]: {x[-1] if x else 'N/A'}")
    assert n >= 5, f"Too few time steps: {n}"
    assert 'x' in d and 'u' in d and 't' in d, "Missing x/u/t"
    print(f"    ✓ valid structure")

print(f"\n  ✓ All {len(data_files)} experiment(s) have valid output")
PYEOF

if [ ! -f "$EXP_DIR/plots.png" ]; then
    echo -e "${RED}ADVERTENCIA: Los datos se generaron, pero 'plots.png' no existe.${NC}"
    echo "Revisa si el JSON tiene activada la opción de graficado."
fi

VERIFY_EXIT=$?

if [ $VERIFY_EXIT -eq 0 ]; then
    echo -e "\n${GREEN}╔══════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║   ✓ FIGURE 5 COMPLETE — GVSoC Real Delays vs Onestep         ║${NC}"
    echo -e "${GREEN}╚══════════════════════════════════════════════════════════════╝${NC}"
    echo -e "${GREEN}   Results: $EXP_DIR${NC}"
    echo -e "${GREEN}   Flask logs: /tmp/flask_figure5.log${NC}"
        # ── Generate plots: build experiment_list_data_incremental.json ─────
    echo -e "\n${YELLOW}[8/8] Preparing plot input and running generate_example_figures.py...${NC}"
    mkdir -p "$EXP_DIR/latest"
    EXP_DIR="$EXP_DIR" python3 - <<PY
import os, json, glob
exp_dir = os.path.abspath(os.environ['EXP_DIR'])
out_dir = os.path.join(exp_dir, 'latest')
os.makedirs(out_dir, exist_ok=True)
data = {}
for f in sorted(glob.glob(os.path.join(exp_dir, '**', 'simulation_data_incremental.json'), recursive=True)):
    sim = json.load(open(f))
    cfg_path = os.path.join(os.path.dirname(f), 'config.json')
    cfg = json.load(open(cfg_path)) if os.path.exists(cfg_path) else {}
    exp_data = {k: sim.get(k, []) for k in ('k','t','x','u','w')}
    exp_data['pending_computations'] = sim.get('pending_computation', sim.get('pending_computations', []))
    exp_data['batches'] = sim.get('batches', None)
    label = os.path.basename(os.path.dirname(f)) or os.path.basename(f)
    # Ensure unique keys
    key = label
    i = 1
    while key in data:
        key = f"{label}_{i}"; i += 1
    data[key] = {
        "label": label,
        "experiment directory": "/home/dcuser/examples/acc_example/latest",
        "experiment data": exp_data,
        "experiment config": cfg
    }
with open(os.path.join(out_dir, 'experiment_list_data_incremental.json'), 'w') as fh:
    json.dump(data, fh, indent=2)
print('Wrote', os.path.join(out_dir, 'experiment_list_data_incremental.json'))
PY

    docker run --rm \
      -u "$(id -u):$(id -g)" \
      -v "${EXP_DIR}:/home/dcuser/examples/acc_example/experiments" \
      -v "${EXP_DIR}/latest:/home/dcuser/examples/acc_example/latest" \
      -w /home/dcuser/examples/acc_example \
      sharc-gvsoc:latest \
      python3 generate_example_figures.py

    PLOTS_PNG="$EXP_DIR/latest/plots.png"
    if [ -f "$PLOTS_PNG" ]; then
      echo -e "${GREEN}✓ Plots generated: $PLOTS_PNG${NC}"
      # Open the generated figure automatically for quick inspection.
      if command -v code >/dev/null 2>&1; then
        code -r "$PLOTS_PNG" >/dev/null 2>&1 || true
        echo -e "${GREEN}✓ Opened plot in VS Code${NC}"
      elif command -v xdg-open >/dev/null 2>&1; then
        xdg-open "$PLOTS_PNG" >/dev/null 2>&1 &
        echo -e "${GREEN}✓ Opened plot with system viewer${NC}"
      else
        echo -e "${YELLOW}No viewer command found (code/xdg-open).${NC}"
      fi
    else
      echo -e "${RED}ERROR: plots.png not found in $EXP_DIR/latest${NC}"
    fi
else
    echo -e "${RED}ERROR: Result validation failed${NC}"
    exit 1
fi
